name: Build Laravel project
on: ["push", "pull_request"]
jobs:
  laravel-and-deploy:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2

       - name: Coveralls GitHub Action
            uses: coverallsapp/github-action@v1.1.2
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}

