name: Build Laravel project

on: push

jobs:

  laravel-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer:v2
          coverage: none

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Install Dependencies (PHP vendors)
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sql

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run production


      - name: Run migration and tests
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: database/database.sql
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_DRIVER: sync
        run: ./vendor/bin/pest --coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
