name: Build Laravel project
on: ["push", "pull_request"]
jobs:
  laravel-and-deploy:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2

       - name: Coveralls
          uses: coverallsapp/github-action@master
          with:
            github-token: ${{ secrets.COVERALLS_TOKEN }}

